export const States = {
  IDLE: 'IDLE',
  DISCOVERING: 'DISCOVERING',
  WIFI_CONNECTING: 'WIFI_CONNECTING',
  DISCONNECTING: 'DISCONNECTING',
  SIGNALING: 'SIGNALING',
  WEBRTC_CONNECTING: 'WEBRTC_CONNECTING',
  CONNECTED: 'CONNECTED',
  BT_SCANNING: 'BT_SCANNING',
  BT_CONNECTING: 'BT_CONNECTING',
  BT_CONNECTED: 'BT_CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  ERROR: 'ERROR',
};

export const Tiers = {
  NONE: 'NONE',
  LAN: 'LAN',
  WIFI_DIRECT: 'WIFI_DIRECT',
  BLUETOOTH: 'BLUETOOTH',
};
